<?xml version="1.0" encoding="UTF-8" ?>
<Package name="pepper_block_app" format_version="4">
    <Manifest src="manifest.xml" />
    <BehaviorDescriptions>
        <BehaviorDescription name="behavior" src="behavior_1" xar="behavior.xar" />
    </BehaviorDescriptions>
    <Dialogs />
    <Resources>
        <File name="index" src="html/index.html" />
        <File name="styles" src="html/css/styles.css" />
        <File name="main" src="html/js/main.js" />
        <File name="jquery-2.1.3" src="html/libs/jquery-2.1.3.js" />
        <File name="jquery-2.1.3.min" src="html/libs/jquery-2.1.3.min.js" />
        <File name="jquery" src="html/libs/jquery-ui-1.11.2/external/jquery/jquery.js" />
        <File name="ui-bg_diagonals-thick_18_b81900_40x40" src="html/libs/jquery-ui-1.11.2/images/ui-bg_diagonals-thick_18_b81900_40x40.png" />
        <File name="ui-bg_diagonals-thick_20_666666_40x40" src="html/libs/jquery-ui-1.11.2/images/ui-bg_diagonals-thick_20_666666_40x40.png" />
        <File name="ui-bg_flat_10_000000_40x100" src="html/libs/jquery-ui-1.11.2/images/ui-bg_flat_10_000000_40x100.png" />
        <File name="ui-bg_glass_100_f6f6f6_1x400" src="html/libs/jquery-ui-1.11.2/images/ui-bg_glass_100_f6f6f6_1x400.png" />
        <File name="ui-bg_glass_100_fdf5ce_1x400" src="html/libs/jquery-ui-1.11.2/images/ui-bg_glass_100_fdf5ce_1x400.png" />
        <File name="ui-bg_glass_65_ffffff_1x400" src="html/libs/jquery-ui-1.11.2/images/ui-bg_glass_65_ffffff_1x400.png" />
        <File name="ui-bg_gloss-wave_35_f6a828_500x100" src="html/libs/jquery-ui-1.11.2/images/ui-bg_gloss-wave_35_f6a828_500x100.png" />
        <File name="ui-bg_highlight-soft_100_eeeeee_1x100" src="html/libs/jquery-ui-1.11.2/images/ui-bg_highlight-soft_100_eeeeee_1x100.png" />
        <File name="ui-bg_highlight-soft_75_ffe45c_1x100" src="html/libs/jquery-ui-1.11.2/images/ui-bg_highlight-soft_75_ffe45c_1x100.png" />
        <File name="ui-icons_222222_256x240" src="html/libs/jquery-ui-1.11.2/images/ui-icons_222222_256x240.png" />
        <File name="ui-icons_228ef1_256x240" src="html/libs/jquery-ui-1.11.2/images/ui-icons_228ef1_256x240.png" />
        <File name="ui-icons_ef8c08_256x240" src="html/libs/jquery-ui-1.11.2/images/ui-icons_ef8c08_256x240.png" />
        <File name="ui-icons_ffd27a_256x240" src="html/libs/jquery-ui-1.11.2/images/ui-icons_ffd27a_256x240.png" />
        <File name="ui-icons_ffffff_256x240" src="html/libs/jquery-ui-1.11.2/images/ui-icons_ffffff_256x240.png" />
        <File name="index" src="html/libs/jquery-ui-1.11.2/index.html" />
        <File name="jquery-ui" src="html/libs/jquery-ui-1.11.2/jquery-ui.css" />
        <File name="jquery-ui" src="html/libs/jquery-ui-1.11.2/jquery-ui.js" />
        <File name="jquery-ui.min" src="html/libs/jquery-ui-1.11.2/jquery-ui.min.css" />
        <File name="jquery-ui.min" src="html/libs/jquery-ui-1.11.2/jquery-ui.min.js" />
        <File name="jquery-ui.structure" src="html/libs/jquery-ui-1.11.2/jquery-ui.structure.css" />
        <File name="jquery-ui.structure.min" src="html/libs/jquery-ui-1.11.2/jquery-ui.structure.min.css" />
        <File name="jquery-ui.theme" src="html/libs/jquery-ui-1.11.2/jquery-ui.theme.css" />
        <File name="jquery-ui.theme.min" src="html/libs/jquery-ui-1.11.2/jquery-ui.theme.min.css" />
        <File name="ajax-loader" src="html/libs/jquery.mobile-1.4.5/images/ajax-loader.gif" />
        <File name="action-black" src="html/libs/jquery.mobile-1.4.5/images/icons-png/action-black.png" />
        <File name="action-white" src="html/libs/jquery.mobile-1.4.5/images/icons-png/action-white.png" />
        <File name="alert-black" src="html/libs/jquery.mobile-1.4.5/images/icons-png/alert-black.png" />
        <File name="alert-white" src="html/libs/jquery.mobile-1.4.5/images/icons-png/alert-white.png" />
        <File name="arrow-d-black" src="html/libs/jquery.mobile-1.4.5/images/icons-png/arrow-d-black.png" />
        <File name="arrow-d-l-black" src="html/libs/jquery.mobile-1.4.5/images/icons-png/arrow-d-l-black.png" />
        <File name="arrow-d-l-white" src="html/libs/jquery.mobile-1.4.5/images/icons-png/arrow-d-l-white.png" />
        <File name="arrow-d-r-black" src="html/libs/jquery.mobile-1.4.5/images/icons-png/arrow-d-r-black.png" />
        <File name="arrow-d-r-white" src="html/libs/jquery.mobile-1.4.5/images/icons-png/arrow-d-r-white.png" />
        <File name="arrow-d-white" src="html/libs/jquery.mobile-1.4.5/images/icons-png/arrow-d-white.png" />
        <File name="arrow-l-black" src="html/libs/jquery.mobile-1.4.5/images/icons-png/arrow-l-black.png" />
        <File name="arrow-l-white" src="html/libs/jquery.mobile-1.4.5/images/icons-png/arrow-l-white.png" />
        <File name="arrow-r-black" src="html/libs/jquery.mobile-1.4.5/images/icons-png/arrow-r-black.png" />
        <File name="arrow-r-white" src="html/libs/jquery.mobile-1.4.5/images/icons-png/arrow-r-white.png" />
        <File name="arrow-u-black" src="html/libs/jquery.mobile-1.4.5/images/icons-png/arrow-u-black.png" />
        <File name="arrow-u-l-black" src="html/libs/jquery.mobile-1.4.5/images/icons-png/arrow-u-l-black.png" />
        <File name="arrow-u-l-white" src="html/libs/jquery.mobile-1.4.5/images/icons-png/arrow-u-l-white.png" />
        <File name="arrow-u-r-black" src="html/libs/jquery.mobile-1.4.5/images/icons-png/arrow-u-r-black.png" />
        <File name="arrow-u-r-white" src="html/libs/jquery.mobile-1.4.5/images/icons-png/arrow-u-r-white.png" />
        <File name="arrow-u-white" src="html/libs/jquery.mobile-1.4.5/images/icons-png/arrow-u-white.png" />
        <File name="audio-black" src="html/libs/jquery.mobile-1.4.5/images/icons-png/audio-black.png" />
        <File name="audio-white" src="html/libs/jquery.mobile-1.4.5/images/icons-png/audio-white.png" />
        <File name="back-black" src="html/libs/jquery.mobile-1.4.5/images/icons-png/back-black.png" />
        <File name="back-white" src="html/libs/jquery.mobile-1.4.5/images/icons-png/back-white.png" />
        <File name="bars-black" src="html/libs/jquery.mobile-1.4.5/images/icons-png/bars-black.png" />
        <File name="bars-white" src="html/libs/jquery.mobile-1.4.5/images/icons-png/bars-white.png" />
        <File name="bullets-black" src="html/libs/jquery.mobile-1.4.5/images/icons-png/bullets-black.png" />
        <File name="bullets-white" src="html/libs/jquery.mobile-1.4.5/images/icons-png/bullets-white.png" />
        <File name="calendar-black" src="html/libs/jquery.mobile-1.4.5/images/icons-png/calendar-black.png" />
        <File name="calendar-white" src="html/libs/jquery.mobile-1.4.5/images/icons-png/calendar-white.png" />
        <File name="camera-black" src="html/libs/jquery.mobile-1.4.5/images/icons-png/camera-black.png" />
        <File name="camera-white" src="html/libs/jquery.mobile-1.4.5/images/icons-png/camera-white.png" />
        <File name="carat-d-black" src="html/libs/jquery.mobile-1.4.5/images/icons-png/carat-d-black.png" />
        <File name="carat-d-white" src="html/libs/jquery.mobile-1.4.5/images/icons-png/carat-d-white.png" />
        <File name="carat-l-black" src="html/libs/jquery.mobile-1.4.5/images/icons-png/carat-l-black.png" />
        <File name="carat-l-white" src="html/libs/jquery.mobile-1.4.5/images/icons-png/carat-l-white.png" />
        <File name="carat-r-black" src="html/libs/jquery.mobile-1.4.5/images/icons-png/carat-r-black.png" />
        <File name="carat-r-white" src="html/libs/jquery.mobile-1.4.5/images/icons-png/carat-r-white.png" />
        <File name="carat-u-black" src="html/libs/jquery.mobile-1.4.5/images/icons-png/carat-u-black.png" />
        <File name="carat-u-white" src="html/libs/jquery.mobile-1.4.5/images/icons-png/carat-u-white.png" />
        <File name="check-black" src="html/libs/jquery.mobile-1.4.5/images/icons-png/check-black.png" />
        <File name="check-white" src="html/libs/jquery.mobile-1.4.5/images/icons-png/check-white.png" />
        <File name="clock-black" src="html/libs/jquery.mobile-1.4.5/images/icons-png/clock-black.png" />
        <File name="clock-white" src="html/libs/jquery.mobile-1.4.5/images/icons-png/clock-white.png" />
        <File name="cloud-black" src="html/libs/jquery.mobile-1.4.5/images/icons-png/cloud-black.png" />
        <File name="cloud-white" src="html/libs/jquery.mobile-1.4.5/images/icons-png/cloud-white.png" />
        <File name="comment-black" src="html/libs/jquery.mobile-1.4.5/images/icons-png/comment-black.png" />
        <File name="comment-white" src="html/libs/jquery.mobile-1.4.5/images/icons-png/comment-white.png" />
        <File name="delete-black" src="html/libs/jquery.mobile-1.4.5/images/icons-png/delete-black.png" />
        <File name="delete-white" src="html/libs/jquery.mobile-1.4.5/images/icons-png/delete-white.png" />
        <File name="edit-black" src="html/libs/jquery.mobile-1.4.5/images/icons-png/edit-black.png" />
        <File name="edit-white" src="html/libs/jquery.mobile-1.4.5/images/icons-png/edit-white.png" />
        <File name="eye-black" src="html/libs/jquery.mobile-1.4.5/images/icons-png/eye-black.png" />
        <File name="eye-white" src="html/libs/jquery.mobile-1.4.5/images/icons-png/eye-white.png" />
        <File name="forbidden-black" src="html/libs/jquery.mobile-1.4.5/images/icons-png/forbidden-black.png" />
        <File name="forbidden-white" src="html/libs/jquery.mobile-1.4.5/images/icons-png/forbidden-white.png" />
        <File name="forward-black" src="html/libs/jquery.mobile-1.4.5/images/icons-png/forward-black.png" />
        <File name="forward-white" src="html/libs/jquery.mobile-1.4.5/images/icons-png/forward-white.png" />
        <File name="gear-black" src="html/libs/jquery.mobile-1.4.5/images/icons-png/gear-black.png" />
        <File name="gear-white" src="html/libs/jquery.mobile-1.4.5/images/icons-png/gear-white.png" />
        <File name="grid-black" src="html/libs/jquery.mobile-1.4.5/images/icons-png/grid-black.png" />
        <File name="grid-white" src="html/libs/jquery.mobile-1.4.5/images/icons-png/grid-white.png" />
        <File name="heart-black" src="html/libs/jquery.mobile-1.4.5/images/icons-png/heart-black.png" />
        <File name="heart-white" src="html/libs/jquery.mobile-1.4.5/images/icons-png/heart-white.png" />
        <File name="home-black" src="html/libs/jquery.mobile-1.4.5/images/icons-png/home-black.png" />
        <File name="home-white" src="html/libs/jquery.mobile-1.4.5/images/icons-png/home-white.png" />
        <File name="info-black" src="html/libs/jquery.mobile-1.4.5/images/icons-png/info-black.png" />
        <File name="info-white" src="html/libs/jquery.mobile-1.4.5/images/icons-png/info-white.png" />
        <File name="location-black" src="html/libs/jquery.mobile-1.4.5/images/icons-png/location-black.png" />
        <File name="location-white" src="html/libs/jquery.mobile-1.4.5/images/icons-png/location-white.png" />
        <File name="lock-black" src="html/libs/jquery.mobile-1.4.5/images/icons-png/lock-black.png" />
        <File name="lock-white" src="html/libs/jquery.mobile-1.4.5/images/icons-png/lock-white.png" />
        <File name="mail-black" src="html/libs/jquery.mobile-1.4.5/images/icons-png/mail-black.png" />
        <File name="mail-white" src="html/libs/jquery.mobile-1.4.5/images/icons-png/mail-white.png" />
        <File name="minus-black" src="html/libs/jquery.mobile-1.4.5/images/icons-png/minus-black.png" />
        <File name="minus-white" src="html/libs/jquery.mobile-1.4.5/images/icons-png/minus-white.png" />
        <File name="navigation-black" src="html/libs/jquery.mobile-1.4.5/images/icons-png/navigation-black.png" />
        <File name="navigation-white" src="html/libs/jquery.mobile-1.4.5/images/icons-png/navigation-white.png" />
        <File name="phone-black" src="html/libs/jquery.mobile-1.4.5/images/icons-png/phone-black.png" />
        <File name="phone-white" src="html/libs/jquery.mobile-1.4.5/images/icons-png/phone-white.png" />
        <File name="plus-black" src="html/libs/jquery.mobile-1.4.5/images/icons-png/plus-black.png" />
        <File name="plus-white" src="html/libs/jquery.mobile-1.4.5/images/icons-png/plus-white.png" />
        <File name="power-black" src="html/libs/jquery.mobile-1.4.5/images/icons-png/power-black.png" />
        <File name="power-white" src="html/libs/jquery.mobile-1.4.5/images/icons-png/power-white.png" />
        <File name="recycle-black" src="html/libs/jquery.mobile-1.4.5/images/icons-png/recycle-black.png" />
        <File name="recycle-white" src="html/libs/jquery.mobile-1.4.5/images/icons-png/recycle-white.png" />
        <File name="refresh-black" src="html/libs/jquery.mobile-1.4.5/images/icons-png/refresh-black.png" />
        <File name="refresh-white" src="html/libs/jquery.mobile-1.4.5/images/icons-png/refresh-white.png" />
        <File name="search-black" src="html/libs/jquery.mobile-1.4.5/images/icons-png/search-black.png" />
        <File name="search-white" src="html/libs/jquery.mobile-1.4.5/images/icons-png/search-white.png" />
        <File name="shop-black" src="html/libs/jquery.mobile-1.4.5/images/icons-png/shop-black.png" />
        <File name="shop-white" src="html/libs/jquery.mobile-1.4.5/images/icons-png/shop-white.png" />
        <File name="star-black" src="html/libs/jquery.mobile-1.4.5/images/icons-png/star-black.png" />
        <File name="star-white" src="html/libs/jquery.mobile-1.4.5/images/icons-png/star-white.png" />
        <File name="tag-black" src="html/libs/jquery.mobile-1.4.5/images/icons-png/tag-black.png" />
        <File name="tag-white" src="html/libs/jquery.mobile-1.4.5/images/icons-png/tag-white.png" />
        <File name="user-black" src="html/libs/jquery.mobile-1.4.5/images/icons-png/user-black.png" />
        <File name="user-white" src="html/libs/jquery.mobile-1.4.5/images/icons-png/user-white.png" />
        <File name="video-black" src="html/libs/jquery.mobile-1.4.5/images/icons-png/video-black.png" />
        <File name="video-white" src="html/libs/jquery.mobile-1.4.5/images/icons-png/video-white.png" />
        <File name="action-black" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/action-black.svg" />
        <File name="action-white" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/action-white.svg" />
        <File name="alert-black" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/alert-black.svg" />
        <File name="alert-white" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/alert-white.svg" />
        <File name="arrow-d-black" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/arrow-d-black.svg" />
        <File name="arrow-d-l-black" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/arrow-d-l-black.svg" />
        <File name="arrow-d-l-white" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/arrow-d-l-white.svg" />
        <File name="arrow-d-r-black" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/arrow-d-r-black.svg" />
        <File name="arrow-d-r-white" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/arrow-d-r-white.svg" />
        <File name="arrow-d-white" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/arrow-d-white.svg" />
        <File name="arrow-l-black" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/arrow-l-black.svg" />
        <File name="arrow-l-white" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/arrow-l-white.svg" />
        <File name="arrow-r-black" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/arrow-r-black.svg" />
        <File name="arrow-r-white" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/arrow-r-white.svg" />
        <File name="arrow-u-black" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/arrow-u-black.svg" />
        <File name="arrow-u-l-black" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/arrow-u-l-black.svg" />
        <File name="arrow-u-l-white" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/arrow-u-l-white.svg" />
        <File name="arrow-u-r-black" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/arrow-u-r-black.svg" />
        <File name="arrow-u-r-white" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/arrow-u-r-white.svg" />
        <File name="arrow-u-white" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/arrow-u-white.svg" />
        <File name="audio-black" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/audio-black.svg" />
        <File name="audio-white" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/audio-white.svg" />
        <File name="back-black" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/back-black.svg" />
        <File name="back-white" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/back-white.svg" />
        <File name="bars-black" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/bars-black.svg" />
        <File name="bars-white" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/bars-white.svg" />
        <File name="bullets-black" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/bullets-black.svg" />
        <File name="bullets-white" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/bullets-white.svg" />
        <File name="calendar-black" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/calendar-black.svg" />
        <File name="calendar-white" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/calendar-white.svg" />
        <File name="camera-black" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/camera-black.svg" />
        <File name="camera-white" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/camera-white.svg" />
        <File name="carat-d-black" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/carat-d-black.svg" />
        <File name="carat-d-white" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/carat-d-white.svg" />
        <File name="carat-l-black" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/carat-l-black.svg" />
        <File name="carat-l-white" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/carat-l-white.svg" />
        <File name="carat-r-black" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/carat-r-black.svg" />
        <File name="carat-r-white" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/carat-r-white.svg" />
        <File name="carat-u-black" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/carat-u-black.svg" />
        <File name="carat-u-white" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/carat-u-white.svg" />
        <File name="check-black" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/check-black.svg" />
        <File name="check-white" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/check-white.svg" />
        <File name="clock-black" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/clock-black.svg" />
        <File name="clock-white" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/clock-white.svg" />
        <File name="cloud-black" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/cloud-black.svg" />
        <File name="cloud-white" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/cloud-white.svg" />
        <File name="comment-black" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/comment-black.svg" />
        <File name="comment-white" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/comment-white.svg" />
        <File name="delete-black" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/delete-black.svg" />
        <File name="delete-white" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/delete-white.svg" />
        <File name="edit-black" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/edit-black.svg" />
        <File name="edit-white" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/edit-white.svg" />
        <File name="eye-black" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/eye-black.svg" />
        <File name="eye-white" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/eye-white.svg" />
        <File name="forbidden-black" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/forbidden-black.svg" />
        <File name="forbidden-white" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/forbidden-white.svg" />
        <File name="forward-black" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/forward-black.svg" />
        <File name="forward-white" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/forward-white.svg" />
        <File name="gear-black" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/gear-black.svg" />
        <File name="gear-white" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/gear-white.svg" />
        <File name="grid-black" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/grid-black.svg" />
        <File name="grid-white" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/grid-white.svg" />
        <File name="heart-black" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/heart-black.svg" />
        <File name="heart-white" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/heart-white.svg" />
        <File name="home-black" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/home-black.svg" />
        <File name="home-white" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/home-white.svg" />
        <File name="info-black" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/info-black.svg" />
        <File name="info-white" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/info-white.svg" />
        <File name="location-black" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/location-black.svg" />
        <File name="location-white" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/location-white.svg" />
        <File name="lock-black" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/lock-black.svg" />
        <File name="lock-white" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/lock-white.svg" />
        <File name="mail-black" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/mail-black.svg" />
        <File name="mail-white" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/mail-white.svg" />
        <File name="minus-black" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/minus-black.svg" />
        <File name="minus-white" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/minus-white.svg" />
        <File name="navigation-black" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/navigation-black.svg" />
        <File name="navigation-white" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/navigation-white.svg" />
        <File name="phone-black" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/phone-black.svg" />
        <File name="phone-white" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/phone-white.svg" />
        <File name="plus-black" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/plus-black.svg" />
        <File name="plus-white" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/plus-white.svg" />
        <File name="power-black" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/power-black.svg" />
        <File name="power-white" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/power-white.svg" />
        <File name="recycle-black" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/recycle-black.svg" />
        <File name="recycle-white" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/recycle-white.svg" />
        <File name="refresh-black" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/refresh-black.svg" />
        <File name="refresh-white" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/refresh-white.svg" />
        <File name="search-black" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/search-black.svg" />
        <File name="search-white" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/search-white.svg" />
        <File name="shop-black" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/shop-black.svg" />
        <File name="shop-white" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/shop-white.svg" />
        <File name="star-black" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/star-black.svg" />
        <File name="star-white" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/star-white.svg" />
        <File name="tag-black" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/tag-black.svg" />
        <File name="tag-white" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/tag-white.svg" />
        <File name="user-black" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/user-black.svg" />
        <File name="user-white" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/user-white.svg" />
        <File name="video-black" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/video-black.svg" />
        <File name="video-white" src="html/libs/jquery.mobile-1.4.5/images/icons-svg/video-white.svg" />
        <File name="jquery.mobile-1.4.5" src="html/libs/jquery.mobile-1.4.5/jquery.mobile-1.4.5.css" />
        <File name="jquery.mobile-1.4.5" src="html/libs/jquery.mobile-1.4.5/jquery.mobile-1.4.5.js" />
        <File name="jquery.mobile-1.4.5.min" src="html/libs/jquery.mobile-1.4.5/jquery.mobile-1.4.5.min.css" />
        <File name="jquery.mobile-1.4.5.min" src="html/libs/jquery.mobile-1.4.5/jquery.mobile-1.4.5.min.js" />
        <File name="jquery.mobile-1.4.5.min" src="html/libs/jquery.mobile-1.4.5/jquery.mobile-1.4.5.min.map" />
        <File name="jquery.mobile.external-png-1.4.5" src="html/libs/jquery.mobile-1.4.5/jquery.mobile.external-png-1.4.5.css" />
        <File name="jquery.mobile.external-png-1.4.5.min" src="html/libs/jquery.mobile-1.4.5/jquery.mobile.external-png-1.4.5.min.css" />
        <File name="jquery.mobile.icons-1.4.5" src="html/libs/jquery.mobile-1.4.5/jquery.mobile.icons-1.4.5.css" />
        <File name="jquery.mobile.icons-1.4.5.min" src="html/libs/jquery.mobile-1.4.5/jquery.mobile.icons-1.4.5.min.css" />
        <File name="jquery.mobile.inline-png-1.4.5" src="html/libs/jquery.mobile-1.4.5/jquery.mobile.inline-png-1.4.5.css" />
        <File name="jquery.mobile.inline-png-1.4.5.min" src="html/libs/jquery.mobile-1.4.5/jquery.mobile.inline-png-1.4.5.min.css" />
        <File name="jquery.mobile.inline-svg-1.4.5" src="html/libs/jquery.mobile-1.4.5/jquery.mobile.inline-svg-1.4.5.css" />
        <File name="jquery.mobile.inline-svg-1.4.5.min" src="html/libs/jquery.mobile-1.4.5/jquery.mobile.inline-svg-1.4.5.min.css" />
        <File name="jquery.mobile.structure-1.4.5" src="html/libs/jquery.mobile-1.4.5/jquery.mobile.structure-1.4.5.css" />
        <File name="jquery.mobile.structure-1.4.5.min" src="html/libs/jquery.mobile-1.4.5/jquery.mobile.structure-1.4.5.min.css" />
        <File name="jquery.mobile.theme-1.4.5" src="html/libs/jquery.mobile-1.4.5/jquery.mobile.theme-1.4.5.css" />
        <File name="jquery.mobile.theme-1.4.5.min" src="html/libs/jquery.mobile-1.4.5/jquery.mobile.theme-1.4.5.min.css" />
        <File name="jquery.ui.dobletap" src="html/libs/jquery.ui.dobletap.js" />
        <File name="jquery.ui.touch-punch" src="html/libs/jquery.ui.touch-punch.js" />
        <File name="knockout-3.2.0.debug" src="html/libs/knockout-3.2.0.debug.js" />
        <File name="jquery.min" src="html/libs/qimessaging/1.0/jquery.min.js" />
        <File name="qimessaging" src="html/libs/qimessaging/1.0/qimessaging.js" />
        <File name="socket.io.min" src="html/libs/qimessaging/1.0/socket.io.min.js" />
        <File name="qimessaging" src="html/libs/qimessaging/2/qimessaging.js" />
    </Resources>
    <Topics />
</Package>
