<?xml version="1.0" encoding="UTF-8" ?>
<Package name="pepper_shounin_app" format_version="4">
    <Manifest src="manifest.xml" />
    <BehaviorDescriptions>
        <BehaviorDescription name="behavior" src="behavior_1" xar="behavior.xar" />
    </BehaviorDescriptions>
    <Dialogs />
    <Resources>
        <File name="package" src="html/PepperResource/pepper_description/package.xml" />
        <File name="pepper" src="html/PepperResource/pepper_description/urdf/pepper1.0_generated_urdf/pepper.json" />
        <File name="pepper" src="html/PepperResource/pepper_description/urdf/pepper1.0_generated_urdf/pepper.urdf" />
        <File name="pepper" src="html/PepperResource/pepper_description/urdf/pepper1.0_generated_urdf/pepper.xml" />
        <File name="pepper_arms" src="html/PepperResource/pepper_description/urdf/pepper1.0_generated_urdf/pepper_arms.xacro" />
        <File name="pepper_fingers" src="html/PepperResource/pepper_description/urdf/pepper1.0_generated_urdf/pepper_fingers.xacro" />
        <File name="pepper_head" src="html/PepperResource/pepper_description/urdf/pepper1.0_generated_urdf/pepper_head.xacro" />
        <File name="pepper_legs" src="html/PepperResource/pepper_description/urdf/pepper1.0_generated_urdf/pepper_legs.xacro" />
        <File name="pepper_material" src="html/PepperResource/pepper_description/urdf/pepper1.0_generated_urdf/pepper_material.xacro" />
        <File name="pepper_robot" src="html/PepperResource/pepper_description/urdf/pepper1.0_generated_urdf/pepper_robot.xacro" />
        <File name="pepper_sensors" src="html/PepperResource/pepper_description/urdf/pepper1.0_generated_urdf/pepper_sensors.xacro" />
        <File name="pepper_torso" src="html/PepperResource/pepper_description/urdf/pepper1.0_generated_urdf/pepper_torso.xacro" />
        <File name="pepper_visual_collisions" src="html/PepperResource/pepper_description/urdf/pepper1.0_generated_urdf/pepper_visual_collisions.xacro" />
        <File name="pepper_wheels" src="html/PepperResource/pepper_description/urdf/pepper1.0_generated_urdf/pepper_wheels.xacro" />
        <File name="Uninstall Pepper meshes" src="html/PepperResource/pepper_meshes/Uninstall Pepper meshes.desktop" />
        <File name="HeadPitch" src="html/PepperResource/pepper_meshes/meshes/1.0/HeadPitch.dae" />
        <File name="HeadYaw" src="html/PepperResource/pepper_meshes/meshes/1.0/HeadYaw.dae" />
        <File name="HipPitch" src="html/PepperResource/pepper_meshes/meshes/1.0/HipPitch.dae" />
        <File name="HipRoll" src="html/PepperResource/pepper_meshes/meshes/1.0/HipRoll.dae" />
        <File name="KneePitch" src="html/PepperResource/pepper_meshes/meshes/1.0/KneePitch.dae" />
        <File name="LElbowRoll" src="html/PepperResource/pepper_meshes/meshes/1.0/LElbowRoll.dae" />
        <File name="LElbowYaw" src="html/PepperResource/pepper_meshes/meshes/1.0/LElbowYaw.dae" />
        <File name="LFinger11" src="html/PepperResource/pepper_meshes/meshes/1.0/LFinger11.dae" />
        <File name="LFinger12" src="html/PepperResource/pepper_meshes/meshes/1.0/LFinger12.dae" />
        <File name="LFinger13" src="html/PepperResource/pepper_meshes/meshes/1.0/LFinger13.dae" />
        <File name="LFinger21" src="html/PepperResource/pepper_meshes/meshes/1.0/LFinger21.dae" />
        <File name="LFinger22" src="html/PepperResource/pepper_meshes/meshes/1.0/LFinger22.dae" />
        <File name="LFinger23" src="html/PepperResource/pepper_meshes/meshes/1.0/LFinger23.dae" />
        <File name="LFinger31" src="html/PepperResource/pepper_meshes/meshes/1.0/LFinger31.dae" />
        <File name="LFinger32" src="html/PepperResource/pepper_meshes/meshes/1.0/LFinger32.dae" />
        <File name="LFinger33" src="html/PepperResource/pepper_meshes/meshes/1.0/LFinger33.dae" />
        <File name="LFinger41" src="html/PepperResource/pepper_meshes/meshes/1.0/LFinger41.dae" />
        <File name="LFinger42" src="html/PepperResource/pepper_meshes/meshes/1.0/LFinger42.dae" />
        <File name="LFinger43" src="html/PepperResource/pepper_meshes/meshes/1.0/LFinger43.dae" />
        <File name="LShoulderPitch" src="html/PepperResource/pepper_meshes/meshes/1.0/LShoulderPitch.dae" />
        <File name="LShoulderRoll" src="html/PepperResource/pepper_meshes/meshes/1.0/LShoulderRoll.dae" />
        <File name="LThumb1" src="html/PepperResource/pepper_meshes/meshes/1.0/LThumb1.dae" />
        <File name="LThumb2" src="html/PepperResource/pepper_meshes/meshes/1.0/LThumb2.dae" />
        <File name="LWristYaw" src="html/PepperResource/pepper_meshes/meshes/1.0/LWristYaw.dae" />
        <File name="juliette_ear" src="html/PepperResource/pepper_meshes/meshes/1.0/Materials/juliette_ear.mat" />
        <File name="juliette_eyes" src="html/PepperResource/pepper_meshes/meshes/1.0/Materials/juliette_eyes.mat" />
        <File name="juliette_face" src="html/PepperResource/pepper_meshes/meshes/1.0/Materials/juliette_face.mat" />
        <File name="milky_white" src="html/PepperResource/pepper_meshes/meshes/1.0/Materials/milky_white.mat" />
        <File name="shiny_white" src="html/PepperResource/pepper_meshes/meshes/1.0/Materials/shiny_white.mat" />
        <File name="transparent" src="html/PepperResource/pepper_meshes/meshes/1.0/Materials/transparent.mat" />
        <File name="RElbowRoll" src="html/PepperResource/pepper_meshes/meshes/1.0/RElbowRoll.dae" />
        <File name="RElbowYaw" src="html/PepperResource/pepper_meshes/meshes/1.0/RElbowYaw.dae" />
        <File name="RFinger11" src="html/PepperResource/pepper_meshes/meshes/1.0/RFinger11.dae" />
        <File name="RFinger12" src="html/PepperResource/pepper_meshes/meshes/1.0/RFinger12.dae" />
        <File name="RFinger13" src="html/PepperResource/pepper_meshes/meshes/1.0/RFinger13.dae" />
        <File name="RFinger21" src="html/PepperResource/pepper_meshes/meshes/1.0/RFinger21.dae" />
        <File name="RFinger22" src="html/PepperResource/pepper_meshes/meshes/1.0/RFinger22.dae" />
        <File name="RFinger23" src="html/PepperResource/pepper_meshes/meshes/1.0/RFinger23.dae" />
        <File name="RFinger31" src="html/PepperResource/pepper_meshes/meshes/1.0/RFinger31.dae" />
        <File name="RFinger32" src="html/PepperResource/pepper_meshes/meshes/1.0/RFinger32.dae" />
        <File name="RFinger33" src="html/PepperResource/pepper_meshes/meshes/1.0/RFinger33.dae" />
        <File name="RFinger41" src="html/PepperResource/pepper_meshes/meshes/1.0/RFinger41.dae" />
        <File name="RFinger42" src="html/PepperResource/pepper_meshes/meshes/1.0/RFinger42.dae" />
        <File name="RFinger43" src="html/PepperResource/pepper_meshes/meshes/1.0/RFinger43.dae" />
        <File name="RShoulderPitch" src="html/PepperResource/pepper_meshes/meshes/1.0/RShoulderPitch.dae" />
        <File name="RShoulderRoll" src="html/PepperResource/pepper_meshes/meshes/1.0/RShoulderRoll.dae" />
        <File name="RThumb1" src="html/PepperResource/pepper_meshes/meshes/1.0/RThumb1.dae" />
        <File name="RThumb2" src="html/PepperResource/pepper_meshes/meshes/1.0/RThumb2.dae" />
        <File name="RWristYaw" src="html/PepperResource/pepper_meshes/meshes/1.0/RWristYaw.dae" />
        <File name="Torso" src="html/PepperResource/pepper_meshes/meshes/1.0/Torso.dae" />
        <File name="WheelB" src="html/PepperResource/pepper_meshes/meshes/1.0/WheelB.dae" />
        <File name="WheelFL" src="html/PepperResource/pepper_meshes/meshes/1.0/WheelFL.dae" />
        <File name="WheelFR" src="html/PepperResource/pepper_meshes/meshes/1.0/WheelFR.dae" />
        <File name="juliette_ear" src="html/PepperResource/pepper_meshes/meshes/1.0/juliette_ear.png" />
        <File name="juliette_ear_org" src="html/PepperResource/pepper_meshes/meshes/1.0/juliette_ear_org.png" />
        <File name="juliette_eyes _org" src="html/PepperResource/pepper_meshes/meshes/1.0/juliette_eyes _org.png" />
        <File name="juliette_eyes" src="html/PepperResource/pepper_meshes/meshes/1.0/juliette_eyes.png" />
        <File name="juliette_face" src="html/PepperResource/pepper_meshes/meshes/1.0/juliette_face.png" />
        <File name="juliette_face_org" src="html/PepperResource/pepper_meshes/meshes/1.0/juliette_face_org.png" />
        <File name="pepper" src="html/PepperResource/pepper_meshes/meshes/1.0/pepper.material" />
        <File name="package" src="html/PepperResource/pepper_meshes/package.xml" />
        <File name="HelloWorld" src="html/cocos_res/HelloWorld.png" />
        <File name="cmdblock_frame01" src="html/cocos_res/cmdblock_frame01.png" />
        <File name="cmdblock_frame_execute01" src="html/cocos_res/cmdblock_frame_execute01.png" />
        <File name="cmdblock_frame_select01" src="html/cocos_res/cmdblock_frame_select01.png" />
        <File name="frame01" src="html/cocos_res/frame01.png" />
        <File name="frame02" src="html/cocos_res/frame02.png" />
        <File name="icon_dustbox" src="html/cocos_res/icon_dustbox.png" />
        <File name="pepper-icone" src="html/cocos_res/pepper-icone.png" />
        <File name="pepper_all" src="html/cocos_res/pepper_all.jpg" />
        <File name="slider_frame" src="html/cocos_res/slider_frame.png" />
        <File name="slider_volume" src="html/cocos_res/slider_volume.png" />
        <File name="workspace_frame" src="html/cocos_res/workspace_frame.png" />
        <File name="workspace_linehead" src="html/cocos_res/workspace_linehead.png" />
        <File name="workspace_separate_bar" src="html/cocos_res/workspace_separate_bar.png" />
        <File name="styles" src="html/css/styles.css" />
        <File name="stylesTest" src="html/css/stylesTest.css" />
        <File name="index" src="html/index.html" />
        <File name="block_core" src="html/js/block_core.js" />
        <File name="blockdef_basicBlk" src="html/js/blockdef_basicBlk.js" />
        <File name="blockdef_basicDebugBlk" src="html/js/blockdef_basicDebugBlk.js" />
        <File name="blockdef_caffeBlk" src="html/js/blockdef_caffeBlk.js" />
        <File name="main" src="html/js/main.js" />
        <File name="main_test" src="html/js/main_test.js" />
        <File name="HelloWorld" src="html/libs/cocos2d-js-v3.8/HelloWorld.html" />
        <File name="HelloWorld" src="html/libs/cocos2d-js-v3.8/HelloWorld.png" />
        <File name="README" src="html/libs/cocos2d-js-v3.8/README.md" />
        <File name="build" src="html/libs/cocos2d-js-v3.8/build.xml" />
        <File name="cocos2d-js-v3.8" src="html/libs/cocos2d-js-v3.8/cocos2d-js-v3.8.js" />
        <File name="project" src="html/libs/cocos2d-js-v3.8/project.json" />
        <File name="firebug-lite" src="html/libs/firebug-lite.js" />
        <File name="html5-cloud-sdk-v2.2.2" src="html/libs/html5-cloud-sdk-v2.2.2.js" />
        <File name="jquery-2.1.3" src="html/libs/jquery-2.1.3.js" />
        <File name="jquery-2.1.3.min" src="html/libs/jquery-2.1.3.min.js" />
        <File name="jquery.ui.dobletap" src="html/libs/jquery.ui.dobletap.js" />
        <File name="jquery.ui.touch-punch" src="html/libs/jquery.ui.touch-punch.js" />
        <File name="js.cookie-2.0.4.min" src="html/libs/js.cookie-2.0.4.min.js" />
        <File name="js.cookie" src="html/libs/js.cookie.js" />
        <File name="jquery.min" src="html/libs/qimessaging/1.0/jquery.min.js" />
        <File name="qimessaging" src="html/libs/qimessaging/1.0/qimessaging.js" />
        <File name="socket.io.min" src="html/libs/qimessaging/1.0/socket.io.min.js" />
        <File name="qimessaging" src="html/libs/qimessaging/2/qimessaging.js" />
        <File name="three" src="html/libs/three.js" />
        <File name="three.min" src="html/libs/three.min.js" />
        <File name="Detector" src="html/libs/three_js/Detector.js" />
        <File name="stats.min" src="html/libs/three_js/libs/stats.min.js" />
        <File name="ColladaLoader" src="html/libs/three_js/loaders/ColladaLoader.js" />
        <File name="ColladaLoader2" src="html/libs/three_js/loaders/ColladaLoader2.js" />
        <File name="Animation" src="html/libs/three_js/loaders/collada/Animation.js" />
        <File name="AnimationHandler" src="html/libs/three_js/loaders/collada/AnimationHandler.js" />
        <File name="KeyFrameAnimation" src="html/libs/three_js/loaders/collada/KeyFrameAnimation.js" />
        <File name="CSS2DRenderer" src="html/libs/three_js/renderers/CSS2DRenderer.js" />
        <File name="CSS3DRenderer" src="html/libs/three_js/renderers/CSS3DRenderer.js" />
        <File name="CSS3DStereoRenderer" src="html/libs/three_js/renderers/CSS3DStereoRenderer.js" />
        <File name="CanvasRenderer" src="html/libs/three_js/renderers/CanvasRenderer.js" />
        <File name="Projector" src="html/libs/three_js/renderers/Projector.js" />
        <File name="RaytracingRenderer" src="html/libs/three_js/renderers/RaytracingRenderer.js" />
        <File name="SVGRenderer" src="html/libs/three_js/renderers/SVGRenderer.js" />
        <File name="SoftwareRenderer" src="html/libs/three_js/renderers/SoftwareRenderer.js" />
        <File name="project" src="html/project.js" />
        <File name="shounin_proj" src="html/shounin_proj.js" />
        <File name="ShoukonIn - コピー" src="html/cocos_res/ShoukonIn - コピー.png" />
        <File name="ShoukonIn" src="html/cocos_res/ShoukonIn.png" />
        <File name="frame03" src="html/cocos_res/frame03.png" />
    </Resources>
    <Topics />
    <IgnoredPaths />
</Package>
